---
- name: Create a linux service account
  hosts: all
  gather_facts: false
                    
  tasks:

    - name: Create a service account
      user:
        name: "{{ srvacct_username }}"
        comment: "{{ srvacct_description }}"
        password: "{{ srvacct_password | string | password_hash('sha512') }}"
